version: '2'

services:
    php:
        build: .
        restart: always
        links:
            - memcached
            - tarantool
        ports:
            - "9090:9000"
        volumes:
            - ./:/var/www:rw
        working_dir: /var/www
    memcached:
        image: memcached
        restart: always
        mem_limit: 1015MB
        ports:
            - "11211:11211"
        command: ["memcached", "-m 1014"]
    tarantool:
        image: tarantool/tarantool
#        image: tarantool/tarantool:1.8
        restart: always
        mem_limit: 1013MB
        ports:
            - "11311:11311"
        volumes:
            - ./tarantool:/var/lib/tarantool:rw
            - ./memcached.lua:/usr/local/etc/tarantool/instances.enabled/memcached.lua
        command: ["tarantool", "/usr/local/etc/tarantool/instances.enabled/memcached.lua"]
